import type { CreatorConfig, CreatorItem } from "./types.js";

export function generateLuauModule(config: CreatorConfig): string {
  const lines: string[] = [
    "-- Generated by Roblox Creator Automator. Do not edit manually.",
    "local CreatorConfig = {",
    `  UniverseId = ${quote(config.universeId)},`,
    "  GamePasses = {",
    ...renderItems(config.gamePasses ?? []),
    "  },",
    "  DeveloperProducts = {",
    ...renderItems(config.developerProducts ?? []),
    "  },",
    "}",
    "",
    "return CreatorConfig",
    ""
  ];

  return lines.join("\n");
}

function renderItems(items: CreatorItem[]): string[] {
  return items.flatMap((item) => {
    const key = toLuauKey(item.name);
    return [
      `    ${key} = {`,
      `      Id = ${quote(item.id ?? "TODO")},`,
      `      Name = ${quote(item.name)},`,
      `      Price = ${item.price},`,
      "    },"
    ];
  });
}

function toLuauKey(name: string): string {
  const safeIdentifier = name.trim().replace(/[^A-Za-z0-9_]/g, "_");
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(safeIdentifier)) {
    return safeIdentifier;
  }

  return `[${quote(name)}]`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}
